version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Stockholm
  open-pull-requests-limit: 10
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "semver:patch"
  ignore:
  - dependency-name: husky
    versions:
    - "> 4.3.0"
